#!/bin/bash
for i in {1..10}
do
for j in {1..10}
do
mkdir temp$i$j
done 
done

for i in {1..10}
do
for j in {1..10}
do
for k in {1..100}
do


mkdir temp$i$j/temp$k


done 
done
done


filename='Run_functionFast'

for i in {1..100}
do
	echo 'special.index <-'"$i" > "$filename$i"'.R'
	cat predictions.R >> $filename$i'.R'
	chmod +x $filename"$i"'.R'
	
done
